# Generated by Django 5.2.1 on 2025-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3'), (4, 'Phase 4'), (5, 'Phase 5'), (6, 'Phase 6'), (7, 'Phase 7'), (8, 'Phase 8'), (9, 'Phase 9'), (10, 'Phase 10')])),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics')], max_length=20)),
                ('sno', models.IntegerField()),
                ('chapter', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('assignment', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
