# Generated by Django 5.2.1 on 2025-06-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_student_alter_chapterprogress_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='highlight_colors',
        ),
    ]
