# Generated by Django 5.2.1 on 2025-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_userpreferences_highlight_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='highlight_colors',
            field=models.JSONField(default=dict),
        ),
    ]
