services:
  - type: web
    name: studentapp-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: studentapp-db
          property: connectionString

  - type: web
    name: studentapp-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://studentapp-backend.onrender.com

databases:
  - name: studentapp-db
    databaseName: studentapp
    user: studentapp 